# Starship 0.56.0

# Settings
add_newline = false 
command_timeout = 20000

[character]
success_symbol = "[âœ](bold green)"

[cmd_duration]
format = '\[[â± $duration]($style)\]'

[conda]
symbol = "ï„Œ "
format = '\[[$symbol$environment]($style)\]'

[dart]
symbol = "î˜ "
format = '\[[$symbol($version)]($style)\]'

[directory]
read_only = " ï ½"

[elixir]
symbol = "î‰µ "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[git_branch]
symbol = "îœ¥ "
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = "î˜§"
format = '\[[$symbol($version)]($style)\]'

[java]
symbol = "îœ¸ "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
symbol = "ğŸ…º "
format = 'via [$symbol]($style)'

[lua]
symbol = "î˜ "
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = "ï¡š "
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
symbol = "îœ˜ "
format = '\[[$symbol($version)]($style)\]'

[package]
symbol = "ï£– "
format = '\[[$symbol$version]($style)\]'

[perl]
symbol = "î© "
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = "î˜† "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
symbol = "îœ¹"
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = "îœ· "
format = '\[[$symbol($version)]($style)\]'

[swift]
symbol = "ï¯£ "
format = '\[[as $symbol]\]'

[time]
format = '\[[$time]($style)\]'
